src/templates/partials/tx_details.html
modified some things based on analysis by this validator. https://validator.w3.org Though I think the main problem is that there was an unclosed ```<div>```. I think what may be happening is that there might be an open div in the header and then a closed div in the footer. Or there's not. And then each thing thats inserted in between the header and footer may or may not have starting and closing ```<div>```. I need to go through and check though. 
Also, the hidden state mod is from here - 
http://w3c.github.io/html/single-page.html#hidden-state-typehidden
=> html fixes

CMakeLists.txt, src/page.h
The compiler on macOS somehow produces errors due to cast ambiguity, so I made some workarounds.
=> build on mac

.gitignore, main.cpp, src/CmdLineOptions.cpp, src/page.h, src/templates/index2.html, src/tools.cpp, src/tools.h
Currently html template files are read from hdd for each request. This can be slow. So we preload all templates now into template_file map when xmrblocks starts. No more constant reading template files from hdd.
=> Preload template files to improve performance

src/page.h
plus some tiny performance improvements
https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/46
=> fix weird timestamps

README.md
domain for explorer.xmr.my has changed to moneroexplorer.com, changing it in readme.
=> update MoneroExplorer.com url in README

CMakeLists.txt, cmake/FindMonero.cmake, ext/mstch/include/mstch/mstch.hpp, src/page.h, src/tools.cpp
It's been a while since the last time I tried to build the code on Mac and Windows. The changes are:
- fixed some library paths in CMakeLists.txt
- added back linking to easylogging (Otherwise the linker on Mac/Win complains. This also doesn't seem to cause any problem for Linux. Why was this removed previously?)
- explicit cast to `uint64_t` and `bool` for `mstch::map`
- wrap `std::map<const string, mtsch::node>` with an internal class template which defines a custom `operator=()`, since the original one `std::map::oeprator=()` somehow caused a very complicated compile error
=> build on mac and windows

src/page.h, src/templates/rawtx.html
This patch combined with https://github.com/monero-project/monero/pull/2586 will make it easier for CLI users to anonymously broadcast transactions to the network using this explorer running on the hidden network.
=> tx-pusher: support hex string of raw tx

main.cpp, src/MempoolStatus.cpp, src/page.h
Fix for the following warnings:
```
~/onion-monero-blockchain-explorer/src/MempoolStatus.cpp:61:37: warning: equality comparison result unused [-Wunused-comparison]
loop_index == 0;
~~~~~~~~~  ~~^~~~
~/onion-monero-blockchain-explorer/src/MempoolStatus.cpp:61:37: note: use '=' to turn this equality comparison into an assignment
loop_index == 0;
^~
=
In file included from ~/onion-monero-blockchain-explorer/main.cpp:4:
~/onion-monero-blockchain-explorer/src/page.h:3132:17: warning: logical not is only applied to the left hand side of this comparison
[-Wlogical-not-parentheses]
if (!strncmp(decoded_raw_data.c_str(), KEY_IMAGE_EXPORT_FILE_MAGIC, magiclen) == 0)
^                                                                         ~~
~/onion-monero-blockchain-explorer/src/page.h:3132:17: …
```
=> misc fixes to eliminate compiler warnings

src/CmdLineOptions.cpp
Isn't it less confusing this way?
=> set implicit value of enable-json-api to true, just like other enable-* options

CMakeLists.txt, cmake/FindMonero.cmake, main.cpp, src/CmdLineOptions.cpp, src/CurrentBlockchainStatus.cpp, src/CurrentBlockchainStatus.h, src/MempoolStatus.cpp, src/MempoolStatus.h, src/MicroCore.cpp, src/page.h, src/templates/address.html, src/templates/index2.html, src/templates/js/cn_util.js, src/templates/js/config.js, src/tools.cpp, src/tools.h
This is a preliminary PR for the pending stagenet PR: https://github.com/monero-project/monero/pull/3277
=> Support for stagenet

CMakeLists.txt
This allows the monero source code and the libraries to be at independent locations.
=> make more directories configurable

README.md
Remove chainradar link as it is not supporting Aeon block explorer anymore. Replace with https://aeonblocks.com as it does currently support Aeon as an alternative block explorer.
=> Update Readme.md to show aeonblocks.com alternate

CMakeLists.txt, src/MempoolStatus.cpp, src/page.h
To correct the following compile issues http://paste.debian.net/1073040/
applying commit below to aeon branch. (THANKS CAM)
[commit 6a1a6c48f](https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/6a1a6c48f830d1b38baa16e462db1605916c5998)
=> port back to C++11 from C++14

src/page.h, src/templates/block.html
I believe 221fdbf8a88e1aebd188b75e79c8ebaefa4e72d1 is not sufficient as it ignores the higher 64 bits of the difficulty. This is the patch cherry-picked from #172.
=> support 128 bit difficulty type

src/rpccalls.cpp
Otherwise it repeats displaying
```
2019-04-05 06:10:29.521	  0x7000053a5000	INFO	global	contrib/epee/src/net_ssl.cpp:75	Generating SSL certificate
mempool status txs: 0
```
while taking an unreasonable amount of CPU load.
=> turn off SSL when connecting to the daemon

main.cpp, src/page.h, src/templates/tx.html
I always liked the idea of having the autorefresh option on the `/txt/<tx_hash>` page as well.
I sometimes go there and wait for the confirmations to come in. Autorefreshing the page makes it more of an experience :)
It uses the exact same mechanism and flag (`--enable-autorefresh-option`) already provided by the index page.
=> Add autorefresh on /tx page.

main.cpp
Google Chrome only showed the source code when clicking **Autorefresh** on the main page.
This PR now returns the proper Content-Type.
By the way, firefox never complained and always rendered the **Autorefresh** correctly.
=> Add autorefresh Content-Type.

README.md
The two currently listed URLs are both down.  I have changed them out with three that are all working at the time of this PR.
Note: I put aeonblockexplorer.com as the main one because it has the longest registered domain name (up until 2023-06-01.)  I'm not favoring one over another; just looking at which one is most likely to still be around in the future.
=> Update Block Explorer URLs in README.md

src/page.h
Adding the count of confirmations (tx_confirmations) enables this API to prove that a transaction has been both sent and confirmed in the blockchain.
Ref: https://github.com/bisq-network/bisq/pull/4378#issuecomment-669629274
=> Add tx_confirmations to resultset in api/outputs

src/page.h
Reverts moneroexamples/onion-monero-blockchain-explorer#224
as it causes issues with v17 branch of monero
https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/225
=> Revert "addopt byte_slice"

README.md, src/templates/css/style.css, src/templates/partials/tx_details.html
fixed safari iPhone issue where Prove Sending fields appear when user is in Decode outputs tab
Closes #237 
To reproduce issue:
1. go to xmrchain.net on safari using iPhone
2. select any transaction
3. Go to Decout Outputs tab
4. see the Prove Sending inputs appearing when user is on the Decode outputs tab
=> iPhone Mobile view fix

Dockerfile
Allows xmrblocks to be run in a docker container, you just need to mount the blockchain folder to the appropriate location. Takes just over an hour to build from scratch.
```sh
docker build --no-cache -t xmrblocks .
docker run --net=host -v xmrdata:/home/monero/.bitmonero xmrblocks
```
Using multistage docker builds, it's possible to copy just the `xmrblocks` binary and its dynamic libraries so the resulting image is under 200MB:
```
❯ sudo docker images                                                                     
[sudo] password for victor:                                                              
REPOSITORY      TAG       IMAGE ID       CREATED          SIZE 
xmrblocks       latest    9e98882d4110   17 minutes ago   179MB 
```
=> dockerized xmrblocks

README.md, main.cpp, src/CmdLineOptions.cpp, src/CurrentBlockchainStatus.cpp, src/CurrentBlockchainStatus.h, src/MempoolStatus.cpp, src/MempoolStatus.h, src/page.h, src/rpccalls.cpp, src/rpccalls.h
Just a simple fix, as "daemon" was misspelled "deamon", even in the flag/arg.
=> Correct misspelling of "daemon" for "daemon-url"

Dockerfile, README.md
This PR fixes an issue with the entrypoint/CMD usage in the Dockerfile, both fixing an issue that would cause the container to not start, and allowing passing different flags to override.
=> Fix Dockerfile CMD/entrypoint

src/MempoolStatus.cpp, src/MicroCore.cpp, src/page.h, src/tools.cpp, src/tools.h
At the next hard fork, wallets will construct tx's where each output has a "view tag" stored on it. It's meant to speed up wallet scanning :) More on it here: https://github.com/monero-project/monero/pull/8061
The smoothest way I could see how to add view tags to outputs in the core repo was by creating a new output type, which I called `txout_to_tagged_key` (after the fork, `txout_to_key` types won't be allowed anymore). This PR is necessary because of that change, unfortunately. To make the change as clean as I could, I added a helper function `get_output_public_key` to the core repo, so you can see in this PR the caller doesn't actually need to know the output type. I got rid of all `txout_to_key` types used in this repo and replaced with that helper function.
Hope you like! :)
=> Update for view tags in next hf

README.md, main.cpp, src/CmdLineOptions.cpp, src/page.h
Current implementation expects `templates` directory to be hosted in the same directory as the `xmrblocks` binary.  This PR removes this constraint and enables a CLI option to specify the path to the `/templates` directory
=> Add a CLI option to specify the templates path

src/templates/css/style.css
Long strings without spaces don't get wrapped and will result in the text overflowing outside of the cell and messing up the structure of the page. See for example [the tx_extra field in this transaction](https://xmrchain.net/search?value=1ecce7898a4e1c7334241c834ba4866d6b511ee896c318b3445aea1cc926e40f).
This small patch makes long text wrap inside the given limit, which is otherwise "ignored".
=> css: fix overflowing text in cells

.github/containerscan/allowedlist.yaml, .github/dependabot.yml, .github/workflows/trivy-analysis.yml, .github/workflows/update-base-image.yml, .github/workflows/update-image-on-push.yml
Hi there,
This PR is very much a "use if you want, no offense if you don't" PR, but enables Docker image builds automatically:
- Weekly w/o caching to ensure all base images/packages are up to date to remediate vulns via regular updates
- When any commit is pushed, unless the commit only edits README.md
The Docker image is built and pushed to Github Packages and Docker Hub with the `latest` tag and the `MONERO_BRANCH` arg as a tag as well.
Note that for this to push to Docker Hub, you will need to create two repository secrets:
- `DOCKER_USERNAME` - your Docker Hub username
- `DOCKER_PASSWORD` - your Docker Hub password or access token
If you don't want to push to Docker Hub, I can update and remove all relevant Docker Hub configuration.
And if you don't want to build and push images at …
=> Enable Github actions build of Docker image

README.md
This fixes https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/303
I'm not sure why, bit it seems onion-monero-blockchain-explorer is unable to read v2 transaction hashes when the local blockchain is pruned. The easiest fix is to not prune, so I disable it in the example.
(I'm not sure if we also want to include "--fast-block-sync=0" as default, I think it is another discussion about trust. The  "--out-peers=64" parameter is also helpful in some cases, but since I'm not quite sure what's the right number, I didn't include any of my other tweaks in this PR)
=> Remove --prune-blockchain from docker-compose.yml

README.md
I know the opposite should be logical, but for some reason, this is only how it works reliably for me.
When I do the opposite (I set explore dependent on monerod, so docker starts monerod first), then for some reason, expore is unable to start. The logs are empty and the webpage is down. For some reason, the `explore` service can't even be restarted with `docker compose down explore`, then `docker compose up -d explore`, because it hangs just like before.
On the other hand, when I start monerod well after explore, then monerod sometimes hangs on `Loading blockchain from folder /home/monero/.bitmonero/lmdb ...`
No matter how long I wait, it's stuck and I need to force stop the service.
The only solution for me was to start monerod slightly after explore is up.
It would be better to clean …
=> Add dependency for docker compose services

Dockerfile
When running this container alongside a monerod container, the mismatching UID/GID breaks permissions.
This commit resolves that by deleting the default ubuntu user (unused here) and replacing it with the newly created monero user.
=> Correct uid/gid for monero user in Dockerfile

src/MicroCore.cpp, src/MicroCore.h
Fixes double-free memory error bug. The underlying `cryptonote::BlockchainDB` pointer is already freed in `cryptnote::Blockchain::deinit()`, called by the destructor. Reference: https://github.com/monero-project/monero/blob/13002ddd4b1ba4b4dcd7c47aa368a87c353b2225/src/cryptonote_core/blockchain.cpp#L545.
=> MicroCore: fix segmentation fault on destructor

CMakeLists.txt
I don't know why this was done since neither Monero core nor xmrblocks needs to link against it. It just breaks builds for no reason.
=> Don't add libcurl as lib dependency

Dockerfile, src/page.h, src/tools.cpp
fixes build for release-v0.18 (v0.18.4.0 will be tagged soon, and will require this fix)
on another note: might be a good idea to build against tags (v0.18.4.0) instead of the branch (release-v0.18)
cherrypicked from [devel](https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/5285f9ca39d406b6de77fd9b60239ce4e5b0b4d0)
=> bump master to v0.18.4.0

CMakeLists.txt
Right now, doesn't build with Moneron on master since it requires C++17
=> Bump to C++17

main.cpp, src/page.h
Currently, the api/outputsblocks can only be used if it is known that the deposit in question has been made recently, no more than 5 blocks ago.
However, if the time of the deposit is unknown, api/outputsblocks cannot be used. The only way to prove a deposit is to request each block with api/block and then call api/outputs for each transactions in that block, which is much less efficient.
For example, if one develops an app that continuously queries blockchain, it can use api/outputsblocks. But, if the app goes offline for longer than 5 blocks, it can no longer use api/outputsblocks and has to iterate over all blocks and all transactions to catch up.
In the api/outputsblocks endpoint, replace the parameter limit with two parameters startblock and endblock. An example request would look as …
=> Change the limit param to startblock and endblock in api/outputsblocks
